### ISSUE TITLE
Losing Shutter after a day idle maybe Xbee?

### ISSUE THREAD

**Issue by dave4robots** [nexdome/ASCOM#13]
I am losing the shutter communication link after the dome sits idle longer than a day. I have to physically go to the dome to unplug the shuiter power and reboot. Then it works fine.

I have been in habit of checking voltage and I am sure battery is connected to charger because it reads over 13 V when I shut down. So I don't think it is a low bat.

After a day I try to connect again.

When I connect, I can watch it on my security cam. I can command dome to move a little, usually to 340 degrees. Then I tel it to home. No problems and reports back at 0 azimuth. 

Then if I try to open shutter, it says on the SkyX that it is buys, but shutter is not moving.

Inside X2 shutter reports the battery voltage as 0 volts.  

I have tried all I can do disabling USB remotely, power cyclying main motor controller remotely, nothing works.  I have to go up to the dome and power cycle the shutter.

I did not have this problem before new firmware.

Is Xbee maybe losing sync since it stays powered on but main dome motor controller powers down during the day?

Thanks for any help.

**Comment by dave4robots** [comment]
Another related behavior. I just tried a couple times to open and it said 'last open successful' even though the slit does not open.  It reported back after 3 seconds when it normally takes a longer time, and I could see it didn't open on camera. 

Then I told it to close and again after 3 seconds reported 'last close successful.'

This happened to be true. But the false reporting that open was successful makes me worried that if I had it running automated it might report back close successful when it never moved.  This could be catastrophic if it was raining. 

AFTER this I checked in the X2 driver settings to read the shutter voltage and it still reports 0 volts. Which basically means the main controller and shutter are not communicating.

**Comment by dave4robots** [comment]
Rodolphe said to add this info to this issue: 

I typically turn the main dome controller off because it is connect to a smart WiFi power strip. I leave the shutter powered on because it doesn’t have a way to turn off and on. I park it on the battery charger and it stays there. 

So to get it to talk to the main controller again now I have to unplug the shutter and plug in again.

**Comment by markm75** [comment]
I'm having the same issue pretty much with mine.

**Comment by NameOfTheDragon** [comment]
Closed - stale issue
