### ISSUE TITLE
Controller unresponsive after hitting "Stop" in POTH/SGP in 3.2.0

### ISSUE THREAD

**Issue by donotunplug** [nexdome/ASCOM#16]
When hitting the "Stop" button in either POTH or SGP interface during rotation, software freezes and then "can't connect to dome" error comes up.  At this point the only way to reconnect is to unplug/reconnect BOTH the power and the USB cables.

**Comment by nexdome** [comment]
Did you get a reply from Tim on this issue?

 

Thx

Babak

**Comment by donotunplug** [comment]
Not yet.  His FaceBook comments on other posts suggested he's tied up with some emergency IT work right now.

**Comment by NameOfTheDragon** [comment]
Closed - stale issue
