### ISSUE TITLE
Shutter loses connection randomly and loses sync with position too, causes rotator to not function

### ISSUE THREAD

**Issue by markm75** [nexdome/ASCOM#17]
Documenting the issue here per request from the fb group.

In one session one night i couldnt get the shutter/rotator to connect at all.
Putty commands didnt appear to be working either (just said xb > detect).

At the same time the rotator wouldnt even work via manual button press on the unit.  Tried toggling power on the shutter and then the rotator button worked (toggling the rotator power/usb alone didnt fix things).

At this point i could finally connect to the shutter and the nexdome panel lit up with shutter info, but it was reading 54% when the shutter was actually closed.  If i hit open it went to 100% on the readout but actually at the 54% position.  Then if you hit close it tried to close beyond the fully closed position causing it to "crash" into the bottom lip of the dome until i shut off the shutter/hit stop.

To clear this odd shutter position error i had to move the dome to park and put the shutter on charge.  Once it hit the charger it went to 0% again.

This is the log from this series of events: http://astronomicallyspeaking.com/public/loglatest.log

Secondarily, on the 25th/26th overnight session, i initially connected and could get the shutter to go up via software, no issues, but i noticed midway through the night the shutter portion was now showing offline for some reason.  I couldnt get the shutter to move when i went out and manually pressed the button, i had to toggle power and could then lower it manually.  Once again once it hit the charger it showed up again in the nexdome panel.

Here is the log file from the 26th.. when i tried to shut it manually it was after 2am i believe and had been offline for several hours in the nexdome panel:

http://astronomicallyspeaking.com/public/12-26logs.log

**Comment by markm75** [comment]
Adding the latest log, this one around 17:26 where it went to an offline configuring state.  This is on firmware 3.2 for both rotator and shutter
http://astronomicallyspeaking.com/public/offlinelisteningbeforemax.log

**Comment by markm75** [comment]
This continues to be an issue, the shutter going into offline configuring mode/listening mode, doesnt recover, the only way to recover is to push the firmware to the rotator with shutter unchecked (with the newest driver it takes at least two tries).  Also the button on the shutter will often go "dead" not respond, have to toggle power to the shutter.

**Comment by markm75** [comment]
This is still a constant issue, any tips to troubleshoot would be great, realize it could be a tricky one though.

Every time it stops, i have to toggle the power button to be able to even move it manually.

**Comment by NameOfTheDragon** [comment]
Closed - stale issue
