### ISSUE TITLE
Prism

### ISSUE THREAD

**Issue by dave4robots** [nexdome/ASCOM#21]
I am trialing Prism observatory software. It is supposed to work with ascom. It lets me select the Nexdome ascom driver but then gives me error message on connect. When it does connect gives error message on skew. Does not report open/close correctly.

I have seen on Prism forum that a few people tried Nexdome on the previous ascom driver but gave up.  Do you know if anybody has got prism to work?

Otherwise, I am using TheSkyX and I have used dome successfully both with Rodolphe’s x2 driver and with ascom driver. 

Just wanted prism for automation.

**Comment by dave4robots** [comment]
for what its worth...

i stopped trying to use Prism because I am trying out Voyager. So far, Voyager is superior in how it interfaces with theskyx and ascom. It also has a better user interface and is cheaper.

**Comment by NameOfTheDragon** [comment]
I've seen some pretty funky code in the prism codebase (such as an ASCOM Switch driver that's used for plate solving!) so I suspect the problems are on that end. If the ASCOM driver works with one program but not another, then the program is the problem, not the driver. You can get confirmation of the driver correctness by running the ASCOM validation utility "Conform" against the driver and that is a definitive indication that the driver is "correct".

That said, there have been a few firmware issues which - being charitable - perhaps Prism was preferentially affected by. It might be worth re-trying with the upcoming firmware release 3.3.0 (out later today) and ASCOM driver release 3.1.0 (today or tomorrow).

If the problems still persist, then you are welcome to re-open this issue, but I'm closing it for now as "won't fix".
