### ISSUE TITLE
Com difficulty rotator

### ISSUE THREAD

**Issue by dave4robots** [nexdome/ASCOM#22]
Updated to driver 3.3.0

I’ve had trouble a couple times out with USB com port dropouts. TheSkyX said com port not recognized or busy. 

I restarted my machine after swapping USB outlets on my Pc and it gave me error message at my log on screen about TA.somethinf.server.exe or something stopped responding. 

I rolled back the rotator firmware to 3.2.1 beta and it is working.

**Comment by dave4robots** [comment]
![D46FE365-1796-4D00-82AA-2FC43EF7F30C](https://user-images.githubusercontent.com/56896618/75633703-e021f800-5bcc-11ea-969a-25b06f97ddf5.jpeg)

**Comment by dave4robots** [comment]
See other post. Looks like this was a bad motor board. Blew in the cold. I think it is working again.

**Comment by NameOfTheDragon** [comment]
Resolved by user
