### ISSUE TITLE
Rotator reporting bad data and not working

### ISSUE THREAD

**Issue by dave4robots** [nexdome/ASCOM#23]
Rotator is reporting it is moving and displaying different degrees as it moves in ascom, but it is definitely not moving IRL.

Front buttons don’t work either.

Can’t move at all.

**Comment by dave4robots** [comment]
Okay, sorry, thought this was an ascom issue because I updated at the same time. But it got really cold here and looks like that killed my motor board. I replaced and it’s working.

**Comment by NameOfTheDragon** [comment]
Resolved by user
